# Generated by Django 2.2.7 on 2019-11-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinionMiningApp', '0002_auto_20191117_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
