# Generated by Django 2.2.7 on 2019-11-20 15:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opinionMiningApp', '0003_delete_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionMiningResult',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('aspectStats', models.TextField()),
                ('deviceName', models.TextField(default='noName')),
                ('reportDate', models.TextField(default='noDate')),
                ('textCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('deviceName', models.TextField(default='noName')),
                ('checkpoint', models.TextField()),
                ('prevCount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='OpinionMiningResults',
        ),
    ]
