# Generated by Django 2.2.7 on 2019-11-20 16:40

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opinionMiningApp', '0004_auto_20191120_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('testerId', models.TextField()),
                ('testDate', models.TextField()),
                ('content', models.TextField()),
                ('sentenceCount', models.IntegerField()),
                ('wordCount', models.IntegerField()),
                ('positiveWordCount', models.IntegerField()),
                ('negativeWordCount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opinionMiningApp.Comment'),
        ),
    ]
