# Generated by Django 2.2.7 on 2019-11-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinionMiningApp', '0007_auto_20191121_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
