# Generated by Django 2.2.7 on 2019-11-21 20:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opinionMiningApp', '0008_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('deviceName', models.TextField(default='noName')),
                ('checkpoint', models.TextField()),
                ('prevCount', models.IntegerField()),
                ('companyName', models.TextField()),
            ],
        ),
    ]
