# Generated by Django 2.2.7 on 2019-12-13 09:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('testerId', models.TextField()),
                ('deviceName', models.TextField()),
                ('testDate', models.TextField()),
                ('content', models.TextField()),
                ('sentenceCount', models.IntegerField()),
                ('wordCount', models.IntegerField()),
                ('positiveWordCount', models.IntegerField()),
                ('negativeWordCount', models.IntegerField()),
                ('companyName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpinionMiningResult',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('aspectStats', models.TextField()),
                ('deviceName', models.TextField(default='noName')),
                ('reportDate', models.TextField(default='noDate')),
                ('textCount', models.IntegerField()),
                ('companyName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('deviceName', models.TextField(default='noName')),
                ('checkpoint', models.TextField()),
                ('prevCount', models.IntegerField()),
                ('companyName', models.TextField()),
            ],
        ),
    ]
